name: Terraform CI

on: 
  push:
    branches: main

jobs:
  terraform: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3